### PR TITLE
add option to auto-detect request host

### LINKED ISSUE #86: Request timeouts when installing packages due to invalid hostname
I'm currently hosting several versions of this library on some AWS instances. I've been having people reporting issues with package installation timeouts, which seem to be stemming from the following line of code:

image

All packages are having their baseUrl set to whatever the server's `config.host` property was set. In theory, this should work with no issues. In practice, however, it is relatively common to have the server's bound hostname different from the hostname client's are using for requests (think of load-balanced servers, for example).

What I think would correct this issue would be swapping over to using the requested hostname in the `http` request, rather than the `config.host` value.

Here's a screencap of the issue clients are running into when trying to use our private `npm` repo:
image

### PR DESCRIPTION
**Pull request by hayes**
This is not quite ready to merge, still needs tests and documentation, but should be good enough to test with.

@benduran does this address your use case?

fixes #86

### CODE REVIEW

**Comment by benduran** [comment]
@hayes This is looking pretty good. I like what you have done with this. I think one additional feature would be nice. Currently, this is allowing either the `config.host` to be used, or whatever is provided on the HTTP request when getting package info. I'm thinking it *may* also be likely to specify custom HTTP header(s) to read for. Something along the lines of:

```
config.host = {
     requestHostHeader: 'x-original-host`, // Customizable
};
```

Something along those lines. Does that seem feasible?

**Comment by hayes** [comment]
That might be possible, but the thing I am not clear about with that is how to determine the protocol when using a custom header.

**Comment by benduran** [comment]
I know the **express** server library provides a `protocol` property on their request objects (which are just extensions of the node `IncomingMessage` class), so I'll have to take a look at how they're getting that information.

**Comment by benduran** [comment]
Actually, as I just submitted that, I found the following:

```
An HTTPS connection has req.connection.encrypted (an object with information about the SSL connection). An HTTP connection doesn't have req.connection.encrypted.
```

Source: http://stackoverflow.com/questions/10348906/how-to-know-if-a-request-is-http-or-https-in-node-js

**Comment by hayes** [comment]
Most people don't do ssl termination in their node apps though, so in node
it may be http, but the the public facing url might be fronted by engine x
or something which does the ssl termination

**Comment by benduran** [comment]
That's a very good point. I think it would be sufficient to enforce users set the correct `protocol` when configuring their instance of μpm. I could *possibly* see an argument override for having some kind of flag that tries to auto detect, based on the request connection.

**Comment by hayes** [comment]
Sorry for the lack of progress on this PR, I've been pretty busy.  I've been thinking about this a lot, and the way this is currently written makes things pretty unpredictable.  I think I want to find something a bit more predicable and consistent.

**Comment by benduran** [comment]
That sounds perfectly reasonable. Anyway I can help with this? Besides thinking about solutions, of course 👍

**Comment by hayes** [comment]
Could you provide me with a little more info on your specific setup, how many different hosts are being hit by clients, is there a load balancer/reverse proxy. If so, does it modify the host/hostname headers, and does it inject any x-forwarded style headers

**Comment by benduran** [comment]
I am currently running two different setups:

1. Hosted on AWS using Elastic Beanstalk. Load balancers are automatically created and put in front of the EC2 instances created in this case. Load balancers support both HTTP and HTTPS endpoints. All Elastic Beanstalk does is create EC2 instances for you, spin up some load balancers, and then spawn more EC2 instances automatically if a certain traffic threshold is hit. It's basically just a hands-off EC2 and ELB setup. Not sure if I have control over the load balancers using Beanstalk, however, so I'll need to look into that.

2. Running on an internal server with nginx sitting in front. Passing `x-forwarded-by` headers in this case, to know which nginx instance is doing the proxying.

**Comment by hayes** [comment]
It sounds like you have 2 main entry points.  One is whatever host or ip is assigned to enginex and the other is the host or up assigned to the cluster beanstalk is creating. 
If I am understanding correctly, you should be able to simply set the host in the config to those endpoints (depending on if it's part of the internal or beanstalk cluster).

For the beanstalk cluster you do have 2 host which an npm client might be trying to talk to, the http and https versions.  In this case you can just specify one or the other, and tarballs for the package will always be fetched over that protocol regardless of what protocol npm is configured with.

The other option is to configure the host field on npm to point to a host that serves the s3 bucket that contains the tarballs (be careful not to also serve the user data).  Then npm will talk to unpm only to get the metadata, and will go directly to s3 for the tarballs.  There is an example s3 policy in my s3 backend you could look at for that. If you use that backend with a similar policy, you can use that s3 bucket as a read only version of unpm that works even if the server goes down which is pretty cool.

**Comment by hayes** [comment]
Sorry fat fingered the close and comment button, could still try to make this work, but it sounds like you may not actually need it. (The host config is only for determining what host to get the tarballs from)

**Pull request closed without merging**
